---
title: "neon_prism"
output: html_document
---

```{r}
load("df_TREE.Rdata")
     
```

```{r}
library(dplyr)

df_TREE_daily<-
df_TREE %>%
  group_by(date) %>%
  summarise(Precip = sum(TFPrecipBulk ))
df_TREE_daily
```

```{r}
plot( df_TREE_daily$date, df_TREE_daily$Precip,ylab="Daily Precip (millimeter)",main="TREE",xlab="",type="l")
```

```{r}
prism<-read.csv("PRISM_ppt_stable_4km_20210101_20211231_45.4937_-89.5857 (1).csv",skip = 10)
prism
```

```{r}
prism$Date<-as.POSIXct(prism$Date, format="%Y-%m-%d")
#save(prism,file="TREE_prism.Rdata")
```

```{r}
plot( df_TREE_daily$date, df_TREE_daily$Precip,ylab="Daily Precip (millimeter)",main="TREE",xlab="",type="l",ylim=c(0,90))
par(new=T)
plot(prism$Date,prism$ppt..mm.,ylim=c(0,90),col="dodgerblue",type="l",xlab="",ylab="")
legend(x = "topleft"       ,        legend=c("PRISM", "NEON"),        fill = c("dodgerblue","black"))
```

```{r}
plot(df_TREE_daily$Precip,prism$ppt..mm.,xlim=c(0,90),ylim=c(0,90),xlab = "NEON",ylab="PRISM")
par(new=T)
plot(seq(-100:100), seq(-100:100), type="l",xlim=c(0,90),ylim=c(0,90), xlab = " ",ylab=" ")
```






```{r}
#df_niwot_daily_2021<-df_niwot_daily[df_niwot_daily$date>= as.POSIXct("2021-10-01" , format="%Y-%m-%d") & df_niwot_daily$date<= as.POSIXct("2022-06-30" , format="%Y-%m-%d") ,]
#plot(df_niwot_daily_2021$date,df_niwot_daily_2021$Precip,ylab="Daily Precip Bulk (millimeter)",main="Niwot (start in Oct 2021)",xlab="",tyle="l",ylim = c(0, 40 ))
#par(new=T)

#prism2021<-prism[prism$Date>= as.POSIXct("2021-10-01" , format="%Y-%m-%d") & prism$Date<=as.POSIXct("2022-06-30" , format="%Y-%m-%d") ,]

#plot(prism2021$Date,prism2021$ppt..mm.,col="dodgerblue" ,ylim = c(0, 40 ),ylab="",xlab="")

#legend(x = "topleft"       ,        legend=c("PRISM", "NEON"),        fill = c("dodgerblue","black"))

```

